### ISSUE TITLE
yamllint stops on first failure

### ISSUE THREAD

**Issue by markdorison** [rasshofer/yaml-lint#10]
`yamllint` seems to currently stop on the first failure it encounters whether checking a signle file or multiple files. It would be great to allow `yamllint` to continue on so as to get a full report.

**Comment by paulo-ferraz-oliveira** [comment]
I believe this is actually on `js-yaml`, since it's causing an exception on the first failure. At least for the "single file" part. Maybe `yaml-lint` could handle continuing for multiple files 🤷

**Comment by rasshofer** [comment]
Better late than never: this has finally been fixed in v1.4.0 which was published a few minutes ago. Sorry for the delay! 🙈
