### ISSUE TITLE
Update plan

### ISSUE THREAD

**Issue by poppinlp** [rasshofer/yaml-lint#13]
Hi. I think there could be some updates. Here's my plan:

- Add help information for CLI
- Support more configuration file formats such as `yaml` (I have seen `.yaml-lint.json` in code but this not mentioned in docs. We may update docs)
- Add test cases for CLI since we only have test cases for linter right now.

I don't know what you think, so I haven't started this yet.
Wait for your reply~ Wish not bother you too much. :)

**Comment by rasshofer** [comment]
First of all, thank you very much for your ongoing effort and dedication, highly appreciated!

Regarding your ideas/plans: I already added some documentation regarding how to specify options with 547f5e0, but if you like you could implement the test cases for the CLI, that would be amazing! :)

**Comment by poppinlp** [comment]
OK, i'll add the test cases for the CLI.
And maybe you could active this repo on [coveralls](https://coveralls.io/) or something like it, so that we can update the code coverage by CI and show it by badge. (I don't have the permission to do this)

**Comment by rasshofer** [comment]
Coveralls has already been enabled: https://coveralls.io/github/rasshofer/yaml-lint :)

[![Coverage Status](https://coveralls.io/repos/github/rasshofer/yaml-lint/badge.svg?branch=master)](https://coveralls.io/github/rasshofer/yaml-lint?branch=master)

**Comment by poppinlp** [comment]
Hi, i've add test cases in [this PR](https://github.com/rasshofer/yaml-lint/pull/15).
