### ISSUE TITLE
yamllint ./foo/file.yml no longer works

### ISSUE THREAD

**Issue by kaelig** [rasshofer/yaml-lint#16]
## Steps to reproduce

```
cd into a directory containing yml files
yamllint ./relative/path/to/any/file.yml
```

### Expected

Linting performed on `file.yml`

### Actual

```
✖ YAML Lint failed.
✖ No YAML files were found matching your selection.
```

### Known workaround

Remove `./` in the path, and it works as expected:

```
yamllint relative/path/to/any/file.yml
```
---

My feeling is that #12 introduced this regression, but I'm not sure.

**Comment by rasshofer** [comment]
Ooops, thanks a lot for the hint! 🙈 This is fixed with v1.2.2.
