### ISSUE TITLE
Added sample .yaml-lint.json to README

### ISSUE THREAD

**Issue by laueian** [rasshofer/yaml-lint#21]
I was looking through the [docs for yamllint](https://yamllint.readthedocs.io) and found that they provide a [default](https://yamllint.readthedocs.io/en/stable/configuration.html) yamllint configuration file to help people get started.

I think it might be helpful to provide a default configuration file in the README of this project. Let me know what you think. I'd be happy to make a PR.

I took the default configuration from the yamllint docs and converted it to JSON | https://gist.github.com/laueian/351d968ce4c93b136c5533c318e616aa

**Comment by pixelastic** [comment]
I think you're on the wrong repo. The link you're referring to seems to be the documentation for `yamllint`, as a python program. While this repository is for the `yamllint` as an npm module.

This repo seems to only check if the yml files have valid syntax, while the python one is checking for my in-depth issues like duplicate keys, trailing spaces, etc.

_I'm no maintainer of either of this projects, but stumble upon your issues while myself trying to more fine-tune configure my yamllint npm module and realized there might be some confusion with another project sharing the same name._

**Comment by rasshofer** [comment]
Sorry for the (very) late feedback on this but @pixelastic is right: this package only shares the same name as the Python package (which is capable of much more things compared to this package right now).

Thus the configuration file is completely different as well.

Sorry if this caused/causes any confusion.
