### ISSUE TITLE
Unable to validate multiple documents in same file.

### ISSUE THREAD

**Issue by anilmann** [rasshofer/yaml-lint#26]
Hi,

I have a scenario where I need to validate multiple yaml documents in same file.
It fails with below error: 
`11:02:44  + ./node_modules/.bin/yamllint test-service.yml
11:02:45  ✖ expected a single document in the stream, but found more
`
e.g.

```
---
test1: abc
---
test1: ac
test2: pyx
```

is it possible to enhance the CLI?

**Comment by rasshofer** [comment]
Better late than never: this has finally been fixed in v1.6.0 which was published a few minutes ago. Sorry for the delay! 🙈
