### ISSUE TITLE
vulnerability in nconf > async

### ISSUE THREAD

**Issue by KITSMoeNashashibi** [rasshofer/yaml-lint#28]
npm audit report:

-----------------------------------------------------------
High            Prototype Pollution in async                                  

Package         async                                                         

Patched in      >=3.2.2                                                       

Dependency of   yaml-lint [dev]                                               

Path            yaml-lint > nconf > async                                     

More info       https://github.com/advisories/GHSA-fwr7-v2mv-hh25

-----------------------------------------------------------

**Comment by paulo-ferraz-oliveira** [comment]
Got the same.

@rasshofer, is the project still alive?

This is a nice `npm` tool, and I've been glad with the results.

**Comment by paulo-ferraz-oliveira** [comment]
I'm gonna pull request for this. I'll also take this chance to introduce GitHub actions to the repo. as a way to ease CI.

**Comment by rasshofer** [comment]
Give me a minute, I wanted to port this package to TypeScript anyways and will update the dependencies accordingly.

**Comment by paulo-ferraz-oliveira** [comment]
Oh, I caught your message only now.

No biggie. You have a pull request. Feel free to close it 😄

**Comment by rasshofer** [comment]
Oh no, sorry about that 😞 

I just published v1.3.0 of the package which brings latest dependencies and TypeScript typings.

Please let me know anytime in case something still isn’t working or causing audit issues.

**Comment by paulo-ferraz-oliveira** [comment]
Sure thing. I'll remove my pull request and fork. Thanks for the update.
