### ISSUE TITLE
yamllint does not work on Windows

### ISSUE THREAD

**Issue by vgolynets** [rasshofer/yaml-lint#31]
On Windows yamllint does not work since v1.3.0. Issue is that globbySync does not understand patterns with back slashes, see related issue https://github.com/sindresorhus/globby/issues/130.

Even if you run yamllint with forward slashes e.g. `yamllint some/path/to/my.yaml`, then call of `resolve(process.cwd(), pattern)` breaks it because converts path to Windows style i.e. `some\path\to\my.yaml`.

Simple solution is to use something like `resolve(process.cwd(), pattern).replace(/\\/g, '/')`.

**Comment by rasshofer** [comment]
Oops, sorry about that. daa4899b5b12054a79f32f1b3092b3ebabb5b63c fixes the issue and I extended the CI pipeline to also run the tests in Windows and macOS to catch such issues in the future. The fixed version has been released as v1.7.0 a few seconds ago.

Thanks for the detailed report, much appreciated! 👍
