### ISSUE TITLE
Validate all yml files in folder

### ISSUE THREAD

**Issue by simlu** [rasshofer/yaml-lint#9]
Would be great if we could run e.g. "yamllint **.yml"

**Comment by poppinlp** [comment]
This is supported already. You could pass globs as CLI input. You may have a try. :)

**Comment by poppinlp** [comment]
Hi. The CLI supports globs input already. You may have a try. :)

**Comment by rasshofer** [comment]
As mentioned by @poppinlp, you should be able to run e.g. `yamllint some/dir/*.yaml` or `yamllint lorem.yaml ipsum.yaml` to check multiple files. Thus I’m closing this issue but feel free to let me know if you have any further problems/issues! :)

**Comment by simlu** [comment]
Thank you for getting back! Does this work when calling from code?

**Comment by rasshofer** [comment]
No, but you could implement it within your script/application by combining the `yamlLint.lintFile` method (which is intended for programmatic use as described by you) and [glob](https://www.npmjs.com/package/glob). Feel free to check out [cli.js](https://github.com/rasshofer/yaml-lint/blob/master/cli.js) where it is implemented exactly like that! :)

**Comment by simlu** [comment]
Kk, makes sense. I believe that's what I ended up doing after I opened this ticket four month ago. Thanks!
